### ISSUE TITLE
Erro ao excluir Agente

### ISSUE THREAD

**Issue by uira** [ForaDoEixo/MapaFDE#9]
Eu estava tentando apagar este agente:
http://foradoeixo.mapas.culturalivre.org/agentes/apaga/51/

E recebi o seguinte erro:

`Fatal error: Uncaught Error: Call to a member function getRevisionData() on null in /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/EntityRevision.php:137 Stack trace: #0 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Entity.php(576): MapasCulturais\Entities\Agent->_newModifiedRevision() #1 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/EntitySoftDelete.php(51): MapasCulturais\Entity->save(true) #2 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controllers/EntityController.php(454): MapasCulturais\Entities\Agent->delete(true) #3 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controllers/EntityController.php(422): MapasCulturais\Controllers\EntityController->DELETE_single() #4 /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(274): MapasCulturais\Controller in /srv/mapas.culturalivre.org/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/EntityRevision.php on line 137`

**Comment by uira** [comment]
Conferi e, apesar do erro, o agente foi excluído (ou, no caso, movido para a lixeira, como esperado)
